/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControlPais;
import Controlador.VerificacionPais;
import Modelo.ArrayPais;

/**
 *
 * @author Che
 */
public class CrearPais extends javax.swing.JFrame {

    /**
     * Creates new form CrearPais
     */
    ControlPais control;
    VerificacionPais verifica;
    ArrayPais pais;
    public CrearPais() {
        initComponents();
        control=new ControlPais(pais,this);
        this.JB_guardar.addActionListener(control);
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_nombre = new javax.swing.JLabel();
        JL_codigo = new javax.swing.JLabel();
        JL_capacidad = new javax.swing.JLabel();
        JL_capacidadR = new javax.swing.JLabel();
        JT_nombre = new javax.swing.JTextField();
        JT_codigo = new javax.swing.JTextField();
        JT_capacidad = new javax.swing.JTextField();
        JT_refugiados = new javax.swing.JTextField();
        JB_guardar = new javax.swing.JButton();
        JL_mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_nombre.setText("Nombre");

        JL_codigo.setText("Codigo");

        JL_capacidad.setText("Capacidad");

        JL_capacidadR.setText("Capacidad Refugiados");

        JB_guardar.setText("Guardar");

        JL_mensaje.setText("Mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_nombre)
                    .addComponent(JL_codigo)
                    .addComponent(JL_capacidad)
                    .addComponent(JL_capacidadR)
                    .addComponent(JB_guardar))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JT_refugiados, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(JT_capacidad)
                            .addComponent(JT_codigo)
                            .addComponent(JT_nombre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JL_nombre)
                    .addComponent(JT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_codigo)
                    .addComponent(JT_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_capacidad)
                    .addComponent(JT_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_capacidadR)
                    .addComponent(JT_refugiados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_guardar)
                    .addComponent(JL_mensaje))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void establecerCapacidad(int capacidad){
        this.JT_capacidad.setText(""+capacidad);
    }
    public int obtenerCapacidad(){
        return Integer.parseInt(this.JT_capacidad.getText());
    }
    public void establecerNombre(String nombre){
        this.JT_nombre.setText(nombre);
    }
    public String  obtenerNombre(){
        return this.JT_nombre.getText();
    }
     public void establecerCodigo(String codigo){
        this.JT_codigo.setText(codigo);
    }
    public String  obtenerCodigo(){
        return this.JT_codigo.getText();
    }
     public void establecerR(int capacidadR){
        this.JT_refugiados.setText(""+capacidadR);
    }
    public int obtenerR(){
        return Integer.parseInt(this.JT_refugiados.getText());
    }
    
    
     public boolean verificarCodigo() {
        boolean codigo=verifica.validaCodigo(this.JT_codigo.getText());
        
        if(!codigo){
            setMensaje(" El formato es P y cuatro digitos");
        }
        return !codigo;
    }
    
    
    public void setMensaje(String mensaje){
         this.JL_mensaje.setText(mensaje);
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_guardar;
    private javax.swing.JLabel JL_capacidad;
    private javax.swing.JLabel JL_capacidadR;
    private javax.swing.JLabel JL_codigo;
    private javax.swing.JLabel JL_mensaje;
    private javax.swing.JLabel JL_nombre;
    private javax.swing.JTextField JT_capacidad;
    private javax.swing.JTextField JT_codigo;
    private javax.swing.JTextField JT_nombre;
    private javax.swing.JTextField JT_refugiados;
    // End of variables declaration//GEN-END:variables
}
