/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlPrincipal;

/**
 *
 * @author Che
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ControlPrincipal control;
    
    public Principal() {
        initComponents();
        control=new ControlPrincipal();
        Salir.addActionListener(control);
        this.GuardarPersona.addActionListener(control);
        this.CrearPais.addActionListener(control);
        this.Xml.addActionListener(control);
        this.JB_generador.addActionListener(control);
        this.JB_buscar.addActionListener(control);
    }
    
    
    public void establecerInter(int intercambio){
        this.JT_intercambio.setText(""+intercambio);
    }
    public int ObtenerInter(){
        return Integer.parseInt(this.JT_intercambio.getText());
    }
    public void setMensage(Object mensaje){
        this.JL_info.setText(""+mensaje);
    }
     public void setContador(int contador){
        this.JL_contador.setText(""+contador);
    }
    public int ObtenerId(){
        return Integer.parseInt(this.JT_idBuscar.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_generador = new javax.swing.JButton();
        JL_intercambio = new javax.swing.JLabel();
        JT_intercambio = new javax.swing.JTextField();
        JL_info = new javax.swing.JLabel();
        JL_idBuscar = new javax.swing.JLabel();
        JT_idBuscar = new javax.swing.JTextField();
        JB_buscar = new javax.swing.JButton();
        JL_contador = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Xml = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        Persona = new javax.swing.JMenu();
        GuardarPersona = new javax.swing.JMenuItem();
        Pais = new javax.swing.JMenu();
        CrearPais = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB_generador.setText("Generador");

        JL_intercambio.setText("Cantidad de intercambios");

        JL_idBuscar.setText("Digite el Id:");

        JB_buscar.setText("Buscar");

        Archivo.setText("Archivo");

        Xml.setText("Xml");
        Archivo.add(Xml);

        Salir.setText("Salir");
        Archivo.add(Salir);

        jMenuBar1.add(Archivo);

        Persona.setText("Persona");

        GuardarPersona.setText("Guardar Persona");
        Persona.add(GuardarPersona);

        jMenuBar1.add(Persona);

        Pais.setText("Pais");

        CrearPais.setText("Crear Pais");
        Pais.add(CrearPais);

        jMenuBar1.add(Pais);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_buscar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_idBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JT_idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JL_intercambio)
                        .addGap(18, 18, 18)
                        .addComponent(JT_intercambio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JL_contador, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JL_info, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JB_generador))
                            .addGap(57, 57, 57)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_idBuscar)
                    .addComponent(JT_idBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_intercambio)
                    .addComponent(JT_intercambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_generador)
                .addGap(31, 31, 31)
                .addComponent(JL_info, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_contador, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem CrearPais;
    private javax.swing.JMenuItem GuardarPersona;
    private javax.swing.JButton JB_buscar;
    private javax.swing.JButton JB_generador;
    private javax.swing.JLabel JL_contador;
    private javax.swing.JLabel JL_idBuscar;
    private javax.swing.JLabel JL_info;
    private javax.swing.JLabel JL_intercambio;
    private javax.swing.JTextField JT_idBuscar;
    private javax.swing.JTextField JT_intercambio;
    private javax.swing.JMenu Pais;
    private javax.swing.JMenu Persona;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem Xml;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
